// src/services/autoFixApplyService.js
// Phase 4b/c: apply a proposed fix_attempt to a real git checkout and
// optionally open a PR via `gh`. Extracted from scripts/autofix-apply.js
// so the orchestration can be exercised with mocked git/gh/db — the
// safety-critical rollback paths (council audit defects #1 + #2) need
// regression coverage and the CLI shape doesn't permit it.
//
// All side-effecting collaborators are injected via `deps`:
//   - db        : { query }                      defaults to ../db
//   - fs        : node fs module                 defaults to require('fs')
//   - runGit    : (cwd, args[]) => string|null   defaults to execFileSync('git', ...)
//   - runGh     : (cwd, args[]) => string        defaults to execFileSync('gh', ...)
//   - logger    : pino-shaped                    defaults to ../utils/logger
//
// runGit returns the trimmed stdout, or null on non-zero exit (the script
// can decide whether that's fatal). runGh THROWS on non-zero exit because
// the apply-step needs to distinguish "PR didn't open" from any other
// failure.

const path = require('path');
const { execFileSync } = require('child_process');

const defaultDeps = () => ({
  db: require('../db'),
  fs: require('fs'),
  logger: require('../utils/logger'),
  runGit: (cwd, args) => {
    try {
      return execFileSync('git', args, { cwd, stdio: 'pipe', encoding: 'utf8' }).trim();
    } catch (err) {
      // Re-throw with stderr so callers can decide; gitTry catches this.
      const wrapped = new Error(err.stderr ? err.stderr.toString() : err.message);
      wrapped.original = err;
      throw wrapped;
    }
  },
  runGh: (cwd, args) =>
    execFileSync('gh', args, { cwd, stdio: 'pipe', encoding: 'utf8' }).trim(),
});

// ---------------------------------------------------------------------------
// Pure builders
// ---------------------------------------------------------------------------

function buildCommitMessage(row) {
  return `fix(autofix): patch spec ${row.test_file_name || 'unknown'} (failure #${row.test_failure_id})

Generated by TestForge auto-fix agent.
Failure signature: ${row.failure_signature || 'n/a'}
Fix attempt:       ${row.id}
Model:             ${row.model_provider || ''}/${row.model_name || ''}
`;
}

function buildPrBody(row, fileRel) {
  return [
    '## Auto-fix proposal from TestForge',
    '',
    `Patches \`${fileRel}\` after failure #${row.test_failure_id} (\`${row.failure_signature || 'no-signature'}\`).`,
    '',
    '### Failure sample',
    '```',
    (row.sample_error_message || '(none)').slice(0, 2000),
    '```',
    '',
    `Generated by \`${row.model_provider || ''}/${row.model_name || ''}\`. Review the diff carefully before merging.`,
    '',
    `_fix_attempt_id: ${row.id}_`,
  ].join('\n');
}

// ---------------------------------------------------------------------------
// File locator
// ---------------------------------------------------------------------------

function locateTargetFile(fs, repo, explicitRel, basename) {
  if (explicitRel) {
    const abs = path.resolve(repo, explicitRel);
    if (!fs.existsSync(abs)) throw new Error(`--file ${explicitRel} not found in repo`);
    return abs;
  }
  if (!basename) throw new Error('Cannot locate target file: no --file and no file_name in DB');

  const matches = [];
  walk(fs, repo, (full) => {
    if (path.basename(full) === basename) matches.push(full);
  });

  if (matches.length === 0) {
    throw new Error(`Target file "${basename}" not found anywhere under ${repo} — pass --file to disambiguate`);
  }
  if (matches.length > 1) {
    const rels = matches.map((m) => path.relative(repo, m)).join(', ');
    throw new Error(`Target file "${basename}" matched ${matches.length} paths (${rels}) — pass --file to disambiguate`);
  }
  return matches[0];
}

function walk(fs, dir, fn) {
  const SKIP = new Set(['node_modules', '.git', 'dist', 'build', '.next', 'coverage', 'var']);
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (SKIP.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(fs, full, fn);
    else fn(full);
  }
}

// ---------------------------------------------------------------------------
// Git helpers
// ---------------------------------------------------------------------------

function makeGit(runGit) {
  const ok = (cwd, ...args) => runGit(cwd, args);
  const tri = (cwd, ...args) => { try { return ok(cwd, ...args); } catch { return null; } };
  return { ok, tri };
}

function ensureGitRepo(fs, runGit, repo) {
  if (!fs.existsSync(path.join(repo, '.git'))) {
    throw new Error(`${repo} is not a git checkout (no .git directory)`);
  }
  runGit(repo, ['rev-parse', '--show-toplevel']);
}

function assertCleanFor(runGit, repo, absFile) {
  const rel = path.relative(repo, absFile).replace(/\\/g, '/');
  const status = runGit(repo, ['status', '--porcelain', '--', rel]);
  if (status) {
    throw new Error(`Target file has uncommitted changes:\n${status}\nCommit or stash before running autofix-apply.`);
  }
}

/**
 * Unwind a partial apply. Order matters and each step is best-effort:
 *  1. Discard working-tree edits to the target file — otherwise the
 *     `checkout` in step 3 fails with "would be overwritten" and we
 *     leak a dirty checkout into the next run's assertCleanFor().
 *  2. If we already pushed the branch, delete the remote ref so a future
 *     proposal with the same branch_name doesn't collide with an orphan.
 *  3. Switch off the bad branch and delete it locally.
 */
function rollback(git, repo, baseBranch, newBranch, { targetRel, pushed, remote }) {
  if (targetRel) git.tri(repo, 'checkout', '--', targetRel);
  if (pushed && remote) git.tri(repo, 'push', remote, '--delete', newBranch);
  git.tri(repo, 'checkout', '--quiet', baseBranch);
  git.tri(repo, 'branch', '-D', newBranch);
}

// ---------------------------------------------------------------------------
// gh
// ---------------------------------------------------------------------------

function openPr(fs, runGh, repo, { branch, base, title, body }) {
  const bodyFile = path.join(repo, `.autofix-pr-body-${Date.now()}.tmp`);
  fs.writeFileSync(bodyFile, body, 'utf8');
  try {
    const out = runGh(repo, [
      'pr', 'create',
      '--head', branch,
      '--base', base,
      '--title', title,
      '--body-file', bodyFile,
    ]);
    const url = out.split('\n').find((l) => /github\.com\//.test(l)) || out;
    const m = url.match(/\/pull\/(\d+)/);
    return { url, number: m ? parseInt(m[1], 10) : null };
  } finally {
    try { fs.unlinkSync(bodyFile); } catch { /* ignore */ }
  }
}

// ---------------------------------------------------------------------------
// DB
// ---------------------------------------------------------------------------

async function loadFixAttempt(db, id) {
  const r = await db.query(
    `SELECT fa.*, tf.failure_signature, tf.sample_error_message,
            pt.file_name AS test_file_name
       FROM fix_attempts fa
       JOIN test_failures tf ON tf.id = fa.test_failure_id
       LEFT JOIN playwright_tests pt ON pt.id = tf.last_test_id
      WHERE fa.id = $1`,
    [id]
  );
  return r.rows[0] || null;
}

async function recordApply(db, id, { status, prUrl, prNumber, errorMessage }) {
  await db.query(
    `UPDATE fix_attempts SET
       status = $2,
       pr_url = COALESCE($3, pr_url),
       pr_number = COALESCE($4, pr_number),
       error_message = COALESCE($5, error_message),
       applied_at = COALESCE(applied_at, NOW()),
       finished_at = NOW()
     WHERE id = $1`,
    [id, status, prUrl || null, prNumber || null, errorMessage || null]
  );
}

// ---------------------------------------------------------------------------
// Orchestrator (the thing the CLI and the tests both call)
// ---------------------------------------------------------------------------

/**
 * @param {object} opts
 * @param {number} opts.fixAttemptId
 * @param {string} opts.repo
 * @param {string?} opts.file        explicit relpath in repo
 * @param {string?} opts.base        base branch (default: current HEAD)
 * @param {boolean} opts.push
 * @param {boolean} opts.openPr      implies push
 * @param {string}  opts.remote      default 'origin'
 * @param {boolean} opts.keepCheckout
 * @param {object?} deps             see top of file
 * @returns {Promise<{
 *   fixAttemptId: number,
 *   status: 'proposed'|'pr_opened',
 *   branchName: string,
 *   targetRel: string,
 *   prUrl: string|null,
 *   prNumber: number|null,
 * }>}
 */
async function applyFix(opts, deps = defaultDeps()) {
  const { db, fs, logger, runGit, runGh } = deps;
  const git = makeGit(runGit);

  const repo = path.resolve(opts.repo);
  ensureGitRepo(fs, runGit, repo);

  const row = await loadFixAttempt(db, opts.fixAttemptId);
  if (!row) throw new Error(`fix_attempts ${opts.fixAttemptId} not found`);
  if (row.status !== 'proposed' && row.status !== 'patching') {
    throw new Error(`fix_attempts ${row.id} is in status="${row.status}" — expected "proposed"`);
  }
  if (!row.new_code) {
    throw new Error(`fix_attempts ${row.id} has no new_code — re-run scripts/autofix.js to regenerate`);
  }
  if (!row.branch_name) {
    throw new Error(`fix_attempts ${row.id} has no branch_name`);
  }

  const target = locateTargetFile(fs, repo, opts.file, row.test_file_name);
  const targetRel = path.relative(repo, target).replace(/\\/g, '/');
  assertCleanFor(runGit, repo, target);

  const baseBranch = opts.base || git.ok(repo, 'rev-parse', '--abbrev-ref', 'HEAD');
  const newBranch = row.branch_name;
  const remote = opts.remote || 'origin';

  // Refuse to overwrite a branch that already exists.
  if (git.tri(repo, 'rev-parse', '--verify', `refs/heads/${newBranch}`)) {
    throw new Error(`Branch ${newBranch} already exists in ${repo} — delete it or rerun the proposal step to get a new branch_name`);
  }

  git.ok(repo, 'checkout', '-b', newBranch);

  // Track which side-effects landed so rollback can unwind only what's real.
  let pushed = false;

  try {
    fs.writeFileSync(target, row.new_code, 'utf8');
    git.ok(repo, 'add', '--', targetRel);

    const msgFile = path.join(repo, `.autofix-commit-msg-${Date.now()}.tmp`);
    fs.writeFileSync(msgFile, buildCommitMessage(row), 'utf8');
    try {
      git.ok(repo, 'commit', '-F', msgFile);
    } finally {
      try { fs.unlinkSync(msgFile); } catch { /* ignore */ }
    }

    let prInfo = null;
    if (opts.push || opts.openPr) {
      git.ok(repo, 'push', '-u', remote, newBranch);
      pushed = true;
    }
    if (opts.openPr) {
      prInfo = openPr(fs, runGh, repo, {
        branch: newBranch,
        base: baseBranch,
        title: `[autofix] patch ${row.test_file_name || 'spec'} (failure #${row.test_failure_id})`,
        body: buildPrBody(row, targetRel),
      });
    }

    if (!opts.keepCheckout) git.ok(repo, 'checkout', baseBranch);

    const finalStatus = prInfo ? 'pr_opened' : 'proposed';
    await recordApply(db, row.id, {
      status: finalStatus,
      prUrl: prInfo ? prInfo.url : null,
      prNumber: prInfo ? prInfo.number : null,
    });

    return {
      fixAttemptId: row.id,
      status: finalStatus,
      branchName: newBranch,
      targetRel,
      prUrl: prInfo ? prInfo.url : null,
      prNumber: prInfo ? prInfo.number : null,
    };
  } catch (err) {
    logger.warn({ err: err.message, fixAttemptId: row.id, pushed }, 'autofix-apply: rolling back');
    rollback(git, repo, baseBranch, newBranch, { targetRel, pushed, remote });
    await recordApply(db, row.id, { status: 'failed', errorMessage: err.message });
    throw err;
  }
}

module.exports = { applyFix, buildCommitMessage, buildPrBody };
