// src/services/playwrightGenerator.js
// Generates Playwright test files from approved CoverageScenarios via OpenAI

const OpenAI = require('openai');
const config = require('../config');
const logger = require('../utils/logger') || console;

const openai = new OpenAI({ apiKey: config.OPENAI_API_KEY });

// ---------------------------------------------------------------------------
// Prompt templates
// ---------------------------------------------------------------------------

const SYSTEM_PROMPT = `You are a senior QA automation engineer who writes production-grade Playwright tests.
You follow these rules strictly:
- TypeScript with strict mode
- Page Object Model (POM) pattern
- data-testid selectors preferred, fallback to accessible roles
- Each test is independent and atomic
- Use test.describe() to group by feature
- Include @tags in test titles for filtering
- Use realistic test data
- Max 10 steps per test
- Include clear assertions with expect()
- No hardcoded waits — use Playwright auto-waiting`;

function buildGenerationPrompt(scenarios, categories) {
  const tags = categories.length > 0 ? categories.join(', ') : 'regression';

  return `Generate Playwright TypeScript test files from these approved test scenarios.

SCENARIOS:
${JSON.stringify(scenarios, null, 2)}

TAGS TO APPLY: ${tags}

OUTPUT FORMAT — respond with ONLY a JSON object, no markdown fences, no explanation:
{
  "specs": [
    {
      "fileName": "feature-name.spec.ts",
      "content": "// full Playwright test file content"
    }
  ],
  "pages": [
    {
      "fileName": "FeaturePage.ts",
      "content": "// full Page Object class"
    }
  ],
  "testData": {
    "fileName": "test-data.json",
    "content": "{ ... realistic test data ... }"
  },
  "config": {
    "fileName": "playwright.config.ts",
    "content": "// Playwright config"
  }
}

RULES:
- Group related scenarios into one spec file
- Create Page Objects for each distinct page referenced
- Extract test data into JSON
- Include a working playwright.config.ts
- Use @${tags.split(',')[0]?.trim() || 'regression'} tags in test titles
- Each test maps 1:1 to a scenario (use scenario title as test name)
- Include the scenario ID as a comment above each test`;
}

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

/**
 * Generate Playwright files from approved scenarios.
 *
 * @param {Object[]} scenarios - Approved CoverageScenario rows from DB
 * @param {string[]} categories - User-selected tags (e.g. ["smoke", "regression"])
 * @returns {Object} { specs, pages, testData, config } — file objects
 */
async function generatePlaywrightFiles(scenarios, categories = []) {
  if (!scenarios || scenarios.length === 0) {
    throw new Error('No scenarios provided for Playwright generation');
  }

  // Slim down scenario payloads to reduce token usage
  const slim = scenarios.map((s) => ({
    id: s.id,
    category: s.category,
    title: s.title,
    summary: s.summary,
    preconditions: s.preconditions,
    testIntent: s.test_intent,
    inputs: s.inputs,
    expectedOutcome: s.expected_outcome,
    priority: s.priority,
  }));

  const prompt = buildGenerationPrompt(slim, categories);

  const response = await openai.chat.completions.create({
    model: 'gpt-4o',
    temperature: 0.2,
    max_tokens: 4096,
    messages: [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: prompt },
    ],
  });

  const raw = response.choices[0]?.message?.content;
  if (!raw) {
    throw new Error('Empty response from OpenAI');
  }

  // Strip markdown fences if present
  const cleaned = raw.replace(/```json\s*/g, '').replace(/```\s*/g, '').trim();

  let parsed;
  try {
    parsed = JSON.parse(cleaned);
  } catch (err) {
    logger.error({ raw }, 'Failed to parse OpenAI Playwright response');
    throw new Error('OpenAI returned invalid JSON for Playwright generation');
  }

  // Log token usage
  const usage = response.usage;
  if (usage) {
    logger.info(
      {
        promptTokens: usage.prompt_tokens,
        completionTokens: usage.completion_tokens,
        totalTokens: usage.total_tokens,
        scenarioCount: scenarios.length,
      },
      'Playwright generation token usage'
    );
  }

  return parsed;
}

// ---------------------------------------------------------------------------
// README generator (no AI needed)
// ---------------------------------------------------------------------------

function generateReadme(storyTitle, scenarioCount, categories) {
  return `# Playwright Tests — ${storyTitle || 'Generated Tests'}

Generated by TestForge on ${new Date().toISOString()}

## Quick Start

\`\`\`bash
npm install
npx playwright install
npx playwright test
\`\`\`

## Details

- **Scenarios**: ${scenarioCount} approved scenarios converted
- **Tags**: ${categories.join(', ') || 'regression'}
- **Pattern**: Page Object Model (POM)

## Filtering by Tag

\`\`\`bash
npx playwright test --grep @smoke
npx playwright test --grep @regression
\`\`\`

## Project Structure

\`\`\`
tests/
├── *.spec.ts          # Test specs
├── pages/             # Page Object classes
├── test-data/         # Test data JSON
├── playwright.config.ts
└── README.md
\`\`\`
`;
}

module.exports = { generatePlaywrightFiles, generateReadme };
