-- Persist the LLM's explanation alongside the patch.
--
-- The auto-fix loop already captures the LLM's reasoning in the response
-- ({newCode, explanation, confidence}) but drops it on the floor after
-- proposeFix returns — never written to a column, never surfaced anywhere
-- a human reviewer sees. That made the open PR show "Generated by gpt-4o.
-- Review the diff carefully" and nothing else; the reviewer had to infer
-- WHY the model made each change from the diff alone.
--
-- Adding explanation here lets buildPrBody embed it in the PR body so the
-- first thing the reviewer sees is the model's own description of what
-- it did and why. Stored as TEXT (no length cap) because explanations
-- are short paragraphs by design (the prompt asks for a one-liner) but
-- a hard cap would cause silent truncation we'd then have to debug.

ALTER TABLE fix_attempts
  ADD COLUMN IF NOT EXISTS explanation TEXT;
